### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by Alvarofsj** [conda-forge/python-cdo-feedstock#11]
Hi,

The windows version still not working. Reffering CDO as it is shown on the CDO Project website does not work and return a WinError 2 (System can't find file). As an example:

"from cdo import *

cdo = Cdo()"

That code returns the reffered above error, with the following  errors, by line:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\cdo.py", line 97, in __init__

    self.operators              = self.getOperators()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cdo.py", line 302, in getOper
ators
    if (parse_version(getCdoVersion(self.CDO)) > parse_version('1.7.0')):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cdo.py", line 44, in getCdoVe
rsion
    proc = subprocess.Popen([path2cdo,'-V'],stderr = subprocess.PIPE,stdout = su
bprocess.PIPE)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child startupinfo)"

**Comment by ocefpaf** [comment]
Unfortunately we don't build `cdo` on Windows, but the `python-cdo` package can be used if you have `cdo` in your system.

I believe they have pre-built binaries on the main webpage.
